CPRG214.OfficeAssets.WebInterface/Models/AssetType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CPRG214.OfficeAssets.WebInterface.Models
{
    public class AssetType
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

    }
}

CPRG214.OfficeAssets.WebInterface/Models/Assets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CPRG214.OfficeAssets.WebInterface.Models
{
    public class Assets
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Tag Number")]
        public string TagNumber { get; set; }
        [Required]
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        [Display(Name = "Serial Number")]
        public string SerialNumber { get; set; }
        [Display(Name="Asset Type")]
        public int AssetTypeId { get; set; }
        [ForeignKey("AssetTypeId"), Display(Name = "Asset Type")]
        public virtual AssetType AssetTypes { get; set; } 

    }
}

CPRG214.OfficeAssets.WebInterface/Models/ErrorViewModel.cs
using System;

namespace CPRG214.OfficeAssets.WebInterface.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CPRG214.OfficeAssets.WebInterface/Models/ViewModel/AssetsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CPRG214.OfficeAssets.WebInterface.Models.ViewModel
{
    public class AssetsViewModel
    {
        public Assets Assets { get; set; }
        public IEnumerable<AssetType> AssetTypes { get; set; }


    }
}

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Controllers/AssetTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CPRG214.OfficeAssets.WebInterface.Data;
using CPRG214.OfficeAssets.WebInterface.Models;
using Microsoft.AspNetCore.Mvc;

namespace CPRG214.OfficeAssets.WebInterface.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AssetTypesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AssetTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.AssetTypes.ToList());
        }

        //GET Create Action Method
        public IActionResult Create()
        {
            return View();
        }

        //POST Create action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AssetType assetTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Add(assetTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assetTypes);
        }

        //GET Edit Action Method
        public async Task<IActionResult> Edit(int? id)
        {
            if(id ==null)
            {
                return NotFound();
            }

            var assetType = await _db.AssetTypes.FindAsync(id);
            if (assetType == null)
            {
                return NotFound();
            }

            return View(assetType);
        }

        //POST Edit action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AssetType assetTypes)
        {
            if(id!=assetTypes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(assetTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assetTypes);
        }

        //GET Details Action Method
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assetType = await _db.AssetTypes.FindAsync(id);
            if (assetType == null)
            {
                return NotFound();
            }

            return View(assetType);
        }

        //GET Delete Action Method
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assetType = await _db.AssetTypes.FindAsync(id);
            if (assetType == null)
            {
                return NotFound();
            }

            return View(assetType);
        }

        //POST Delet action Method
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productTypes = await _db.AssetTypes.FindAsync(id);
            _db.AssetTypes.Remove(productTypes);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
            
        }

    }
}

CPRG214.OfficeAssets.WebInterface/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CPRG214.OfficeAssets.WebInterface.Models;

namespace CPRG214.OfficeAssets.WebInterface.Controllers
{   [Area("Customer")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CPRG214.OfficeAssets.WebInterface/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CPRG214.OfficeAssets.WebInterface.Data;
using CPRG214.OfficeAssets.WebInterface.Models.ViewModel;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CPRG214.OfficeAssets.WebInterface.Controllers
{
    [Area("Admin")]
    public class AssetsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public AssetsViewModel AssetsVM { get; set; }

        public AssetsController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
            AssetsVM = new AssetsViewModel()
            {
                AssetTypes = _db.AssetTypes.ToList(),
                Assets = new Models.Assets()
        };

        }

        public async Task<IActionResult> Index()
        {
            var assets = _db.Assets.Include(m => m.AssetTypes);


            return View(await assets.ToListAsync());
        }

        //Get : Assets Create
        public IActionResult Create()
        {
            return View(AssetsVM);
        }

        //Post : Assets Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            if (!ModelState.IsValid)
            {
                return View(AssetsVM);
            }

            
            _db.Assets.Add(AssetsVM.Assets);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/AssetTypes/Create.cshtml
@model CPRG214.OfficeAssets.WebInterface.Models.AssetType
@{
    ViewData["Title"] = "Create";
}

<br />
<h2 class="text-info">Create Asset Type</h2>

<form method="post" asp-action="Create">
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"> </div>
        <div class="form-group row">
            <div class=" col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control" />

            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>

    </div>
</form>

@section Scripts{ 
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/AssetTypes/Delete.cshtml
@model CPRG214.OfficeAssets.WebInterface.Models.AssetType
@{
    ViewData["Title"] = "Delete";
}

<br />
<h2 class="text-info">Delete Asset Type</h2>

<form method="post" asp-action="Delete">
    <div class="p-4 border rounded">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class=" col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" disabled class="form-control" />

            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" class="btn btn-danger" asp-route-id="@Model.Id" value="Delete" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>

    </div>
</form>

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/AssetTypes/Details.cshtml
@model CPRG214.OfficeAssets.WebInterface.Models.AssetType
@{
    ViewData["Title"] = "Details";
}

<br />
<h2 class="text-info">Asset Type Details</h2>


    <div class="p-4 border rounded">

        <div class="form-group row">
            <div class=" col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" disabled class="form-control" />

            </div>

        </div>
        <br />
        <div class="form-group">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>

    </div>

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/AssetTypes/Edit.cshtml
@model CPRG214.OfficeAssets.WebInterface.Models.AssetType
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2 class="text-info">Edit Asset Type</h2>

<form method="post" asp-action="Edit">
    <div class="p-4 border rounded">
        <input type="hidden" asp-for="Id" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class=" col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control" />

            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" class="btn btn-primary" asp-route-id="@Model.Id" value="Update"/>
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>

    </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/AssetTypes/Index.cshtml
@model IEnumerable<CPRG214.OfficeAssets.WebInterface.Models.AssetType>
@{
    ViewData["Title"] = "Index";
}

<br/> <br/>

<div class="row">
    <div class="col-6">
        <h2 class="text-info">Asset Type List</h2>
    </div>

    <div class="col-6 text-right">
        <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> New Product Type</a>
    </div>

    <br/>
    <div>
        <table class="table table-striped border">
            <tr class="table-info">
                <th>
                    @Html.DisplayNameFor(m=>m.Name)
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m=>item.Name)
                    </td>
                    <td>
                        <partial name="_TableButtonPartial" model="item.Id"/>
                    </td>
                </tr>
            }
        </table>
    </div>

</div>

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/Assets/Create.cshtml
@model CPRG214.OfficeAssets.WebInterface.Models.ViewModel.AssetsViewModel
@using CPRG214.OfficeAssets.WebInterface.Extensions
@{ 
    ViewData["Title"] = "Create";
}

<br />
<h2 class="text-info">Create Asset</h2>

<form method="post">
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"> </div>
        <div class="form-group row">
            <div class=" col-2">
                <label asp-for="Assets.AssetTypes.Name"> </label>
            </div>
            <div class="col-5">
               <select asp-for="@Model.Assets.AssetTypes.Id" asp-items="Model.AssetTypes.ToSelectListItem(Model.Assets.AssetTypeId)" class="form-control"></select>
            </div>
        </div>

        <div class="form-group row">
            <div class=" col-2">
                <label asp-for="Assets.TagNumber"> </label>
            </div>
            <div class="col-5">
                <input asp-for="Assets.TagNumber" class="form-control" />

            </div>
            <span asp-validation-for="Assets.TagNumber" class="text-danger"></span>
        </div><div class="form-group row">
            <div class=" col-2">
                <label asp-for="Assets.Manufacturer"> </label>
            </div>
            <div class="col-5">
                <input asp-for="Assets.Manufacturer" class="form-control" />

            </div>
            <span asp-validation-for="Assets.Manufacturer" class="text-danger"></span>
        </div><div class="form-group row">
            <div class=" col-2">
                <label asp-for="Assets.Description"> </label>
            </div>
            <div class="col-5">
                <input asp-for="Assets.Description" class="form-control" />

            </div>
            <span asp-validation-for="Assets.Description" class="text-danger"></span>
        </div><div class="form-group row">
            <div class=" col-2">
                <label asp-for="Assets.SerialNumber"> </label>
            </div>
            <div class="col-5">
                <input asp-for="Assets.SerialNumber" class="form-control" />

            </div>
            <span asp-validation-for="Assets.SerialNumber" class="text-danger"></span>
        </div>

        <br />
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>

    </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CPRG214.OfficeAssets.WebInterface/Areas/Admin/Views/Assets/Index.cshtml
@model IEnumerable<CPRG214.OfficeAssets.WebInterface.Models.Assets>
@{
    ViewData["Title"] = "Index";
}

<br /> <br />

<div class="row">
    <div class="col-6">
        <h2 class="text-info">Asset List</h2>
    </div>

    <div class="col-6 text-right">
        <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> New Asset</a>
    </div>

    <br />
    <div>
        <table class="table table-striped border">
            <tr class="table-info">
                <th>
                    @Html.DisplayNameFor(m => m.TagNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Manufacturer)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.SerialNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.AssetTypes)
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.AssetTypes.Name)
                </td>
                <td>
                    @Html.DisplayFor(m => item.TagNumber)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Manufacturer)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(m => item.SerialNumber)
                </td>

                <td>
                    <partial name="_TableButtonPartial" model="item.Id" />
                </td>
            </tr>
            }
        </table>
    </div>

</div>

CPRG214.OfficeAssets.WebInterface/Areas/Customer/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CPRG214.OfficeAssets.WebInterface/Areas/Customer/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CPRG214.OfficeAssets.WebInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CPRG214.OfficeAssets.WebInterface</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
</head>
<body>



    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Office Assets</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="AssetTypes" asp-action="Index">Asset Types</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Assets" asp-action="Index">Assets</a></li>
            </ul>

        </div>
        <div>
            <partial name="_LoginPartial" />
        </div>
    </nav>






    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CPRG214.OfficeAssets.WebInterface</p>
        </footer>
    </div>
    <a href="~/Views/Shared/_LoginPartial.cshtml"></a>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CPRG214.OfficeAssets.WebInterface/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<td style="width:900px" class="col-6 text-right">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit", new { id = Model })">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details", new { id = Model })">
            <i class="fas fa-list"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete", new { id = Model })">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>